### ISSUE TITLE
Show folders in search results first

### ISSUE THREAD

**Issue by abhishek-sharma8** [Achrou/goindex-theme-acrou#102]
Hi, thanks for your awesome work. 
I was wondering if there's a way that the search results show the folders first and the files that contain the search query later. I have seen scripts doing that but can't find it.

**Comment by Achrou** [comment]
reference [FAQ](https://github.com/Aicirou/goindex-theme-acrou#FAQ)

> A comma-separated list of sort keys. Valid keys are 'createdTime', 'folder', 'modifiedByMeTime', 'modifiedTime', 'name', 'name_natural', 'quotaBytesUsed', 'recency', 'sharedWithMeTime', 'starred', and 'viewedByMeTime'. Each key sorts ascending by default, but may be reversed with the 'desc' modifier. Example usage: ?orderBy=folder,modifiedTime desc,name. Please note that there is a current limitation for users with approximately one million files in which the requested sort order is ignored.

**Comment by abhishek-sharma8** [comment]
Thanks. Can I hide everything and only show the folders in search results?
