### ISSUE TITLE
404: Not Found

### ISSUE THREAD

**Issue by zhanghack** [Achrou/goindex-theme-acrou#12]
click build get 404: Not Found
![微信截图_20200430225124](https://user-images.githubusercontent.com/64551960/80725034-2516cc00-8b35-11ea-848f-74b51e08f79d.png)

**Comment by Achrou** [comment]
You can use rclone to get auth code

**Comment by om0504** [comment]
same issue on 5/5.
Already got the auth code, after click the "build", pop up 404 not found
突然懂了，如果原作者連結已失效，是否也別放了，我也是去那連結發現沒作用

另，是否有更詳細教程? 實在看不懂怎替換那些js文漸，連在哪裡都不知道...謝謝

**Comment by Achrou** [comment]
@om0504 如果你已經拿到了Auth Code，就只需要將cf裡的代碼替換為這個連接的內容[https://oss.achirou.workers.dev/0:/go2index/index.js?a=view](https://oss.achirou.workers.dev/0:/go2index/index.js?a=view)，裡面具體需要修改的配置有中文說明

**Comment by om0504** [comment]
原來不知道為什麼JS檔點進去都是亂碼，所以才說不會用
下午又試一次能看到正常內容就明白了，已經架設成功，謝謝您
