### ISSUE TITLE
dplayer解析接口问题：当影视文件(夹)名称带单引号时会导致js错误无法播放

### ISSUE THREAD

**Issue by Mmx233** [Achrou/goindex-theme-acrou#121]
应当编辑接口，将js变量vodurl的内容提前url编码一遍或者更换接口

**Comment by Mmx233** [comment]
比如如果是php接口可以这么处理
![image](https://user-images.githubusercontent.com/36563672/89128708-3acbd100-d52a-11ea-903e-41e260fda77a.png)
![image](https://user-images.githubusercontent.com/36563672/89128717-44553900-d52a-11ea-94c9-5e0b2a86d839.png)

**Comment by Achrou** [comment]
下个版本开始将不再提供播放器api，如需自行搭建
