### ISSUE TITLE
最近一直403 求解

### ISSUE THREAD

**Issue by yayaleslie** [Achrou/goindex-theme-acrou#122]
最近除了这个问题 新手 不知道怎么解决 有没有大佬看下

{
 "error": {
  "errors": [
   {
    "domain": "global",
    "reason": "downloadQuotaExceeded",
    "message": "The download quota for this file has been exceeded."
   }
  ],
  "code": 403,
  "message": "The download quota for this file has been exceeded."
 }
}

**Comment by Achrou** [comment]
google drive 下载限额超了

**Comment by yayaleslie** [comment]
> google drive 下载限额超了

这个有没有 解决办法呢
