### ISSUE TITLE
两个建议

### ISSUE THREAD

**Issue by nilaoda** [Achrou/goindex-theme-acrou#13]
1. 建议给文件夹/文件、新窗口打开和下载按钮的:hover增加手形图标
2. 单独映射文件夹似乎不支持搜索，是否可以在此类情况下自动隐藏搜索栏？
3. 中文排序能按照拼音首字母那样排序吗？

**Comment by nilaoda** [comment]
还有一个 能否支持.html/.htm文件直接打开？用Snap2HTML生成了GD的全盘索引，如果能直接打开而不是显示文件内容就完美了↖(^ω^)↗

**Comment by Achrou** [comment]
> 还有一个 能否支持.html/.htm文件直接打开？用Snap2HTML生成了GD的全盘索引，如果能直接打开而不是显示文件内容就完美了↖(^ω^)↗

是指html/htm直接渲染出来吗

**Comment by nilaoda** [comment]
> > 还有一个 能否支持.html/.htm文件直接打开？用Snap2HTML生成了GD的全盘索引，如果能直接打开而不是显示文件内容就完美了arrow_upper_left(^ω^)arrow_upper_right
> 
> 是指html/htm直接渲染出来吗

是的

**Comment by Achrou** [comment]
@nilaoda [效果](https://oss.achirou.workers.dev/0:/Code/html_render/index.html?a=view)，粗略的加了一下

**Comment by nilaoda** [comment]
thx！很赞👍

**Comment by nilaoda** [comment]
> @nilaoda [效果](https://oss.achirou.workers.dev/0:/Code/html_render/index.html?a=view)，粗略的加了一下

遇到了报错：
![image](https://user-images.githubusercontent.com/20772925/80897550-82c13900-8d2c-11ea-9459-4fe94bc74a08.png)

HTML文件大概有4.57MB
