### ISSUE TITLE
希望添加对AIFF以及ALAC编码的M4A音频格式的支持

### ISSUE THREAD

**Issue by LingEmberMaple** [Achrou/goindex-theme-acrou#136]

**Comment by Achrou** [comment]
2.0.8版本新增了音频播放器支持m4a Aicirou/goindex-theme-acrou@cc5ab9ebd44942c665327927c712fc43fb958d50

**Comment by LingEmberMaple** [comment]
https://test.lingembermaple.workers.dev/0:/
里面二首无法正常播放

**Comment by Achrou** [comment]
浏览器不支持这个编码格式，那就没办法了

**Comment by LingEmberMaple** [comment]
了解
