### ISSUE TITLE
请教怎么加favicon

### ISSUE THREAD

**Issue by lloyd18** [Achrou/goindex-theme-acrou#139]
没有favicon看着好难受

**Comment by Achrou** [comment]
```html
<link href="/YOUR_PATH/favicon.ico" rel="icon" type="image/x-icon" />
```
在workers里搜索`<title>`在下面一行加入上面的代码就行了

**Comment by lloyd18** [comment]
> ```html
> 
> <link href="/YOUR_PATH/favicon.ico" rel="icon" type="image/x-icon" />
> 
> ```
> 
> 在workers里搜索`<title>`在下面一行加入上面的代码就行了

那么问题来了，怎么把图标放到指定路径，我之前都是上传到网站根目录。

**Comment by Achrou** [comment]
给他能访问的地址就行了，怎么放，放在哪你自己定

**Comment by lloyd18** [comment]
谢谢，已经OK
