### ISSUE TITLE
视频加载速度问题

### ISSUE THREAD

**Issue by HamzaLiu** [Achrou/goindex-theme-acrou#142]
相同网络环境下，gdshare的速度好像要比本项目快不少，测试了几个文件都是这样，请问是什么原因以及能否改善呢。

**Comment by Achrou** [comment]
怎么测的？

**Comment by HamzaLiu** [comment]
> 怎么测的？

windows装了个实时网速显示插件，打开同一个文件速度前者是1MB/s左右，本项目大概在300kB/s，用potplayer更低，80kB/s。根据几个文件总结的，很有可能不大靠谱哈，我想知道的是原理上来说有没有可能出现这种差别。如果没有可能的话肯定就是网络波动以及其他原因了。

**Comment by Achrou** [comment]
都是走cf流量，没啥一样不一样的

**Comment by HamzaLiu** [comment]
hhh 多谢回复 那就是我这边的问题了
