### ISSUE TITLE
请问【是否渲染文件/文件夹描述 】这一功能应该怎么使用呢

### ISSUE THREAD

**Issue by lizkes** [Achrou/goindex-theme-acrou#143]
index.js的源代码内有这么一个功能。
https://github.com/Aicirou/goindex-theme-acrou/blob/facd77d7f9bc2858d2f50636b0b7ac4311fe402e/go2index/index.js#L84-L88
但是没找到文档里有介绍使用它的方法，应该怎么样去使用呢？

**Comment by Achrou** [comment]
启用改成true,效果看演示站

**Comment by Achrou** [comment]
#53
