### ISSUE TITLE
How to Deploy on Local With Node JS

### ISSUE THREAD

**Issue by NEOIR** [Achrou/goindex-theme-acrou#151]
Hi, Can i Deploy this Repo With NodeJS on my Coputer

Like That npm install and Then npm start Command ?

Thanks.

**Comment by Achrou** [comment]
No,but you can run it indirectly on your own computer using a workers cli.

**Comment by NEOIR** [comment]
Thanks Bro ...

**Comment by viper-adnan** [comment]
> No,but you can run it indirectly on your own computer using a workers cli.

Can I run it on [heroku](https://heroku.com) ?
