### ISSUE TITLE
Show only configured languages

### ISSUE THREAD

**Issue by viper-adnan** [Achrou/goindex-theme-acrou#158]
Hey, My all users uses only one language so the language switching options is totally useless for me. **It should show only those languages which is configured in the** `themeOptions.languages`. If only one language set, then don't show Language switching option. Or if more than one language set than show language switching option for only those languages.

_If you didn't think this is useful. Tell me where to edit it in the code._

**Thanks 🖤**

**Comment by Achrou** [comment]
https://github.com/Achrou/goindex-theme-acrou/blob/facd77d7f9bc2858d2f50636b0b7ac4311fe402e/src/layout/header-aside/components/header-locales/index.vue#L9
