### ISSUE TITLE
does this support onedrive?

### ISSUE THREAD

**Issue by accelerate12138** [Achrou/goindex-theme-acrou#159]
i have googledrive but it's only 15G. i notice that this project has a feature called Multi drive switching. does it means i can use onedrive rather than googledrive? if i can, what should i do? after all, i use onedrive more often.

by the way, it's puzzing that when i use my own api, i can't see anything in my websites, but when i use the api in index.js(the writer doesn't recommend...), it works well. do you know why?thanks!

**Comment by viper-adnan** [comment]
**One Drive not supported.** Maybe @Aicirou will make a seperate branch for that.

**Comment by accelerate12138** [comment]
> **One Drive not supported.** Maybe @Aicirou will make a seperate branch for that.

thanks for telling!maybe i need to find other projects.

**Comment by 13rocky-dev** [comment]
There are many index project that support onedrive on github. Maybe you can try olaindex, zfile, yukidrive and oneindex. But you have to have a server to run these project.

**Comment by accelerate12138** [comment]
> There are many index project that support onedrive on github. Maybe you can try olaindex, zfile, yukidrive and oneindex. But you have to have a server to run these project.

thank you very much!
actually i have tried oneindex before i find this project, but it can't watch the vedio online. and peojects like zfile seem no longer maintained. it's disappointing. 
i have never learned how to use a sever,maybe i will learn it in my spare time......
