### ISSUE TITLE
703行报错

### ISSUE THREAD

**Issue by sorrymyself** [Achrou/goindex-theme-acrou#16]
worker.js:703 Uncaught (in promise) TypeError: Cannot read property '0' of undefined

部署在cf里面，就这样了，网页端是空白

**Comment by Achrou** [comment]
使用readme里的`index.js`文件

**Comment by sorrymyself** [comment]
我试试
2020年5月4日 +0800 18:48 Aicirou <notifications@github.com>，写道：
