### ISSUE TITLE
请问可以更换下面的外部播放器按钮吗？

### ISSUE THREAD

**Issue by xwyrz** [Achrou/goindex-theme-acrou#164]
如果可以。要在哪里修改。

**Comment by Achrou** [comment]
https://github.com/Aicirou/goindex-theme-acrou/blob/facd77d7f9bc2858d2f50636b0b7ac4311fe402e/src/views/page/GoVideo.vue#L185

https://github.com/Aicirou/goindex-theme-acrou/blame/facd77d7f9bc2858d2f50636b0b7ac4311fe402e/src/views/page/GoVideo.vue#L185-L238
