### ISSUE TITLE
Issue in opening the video after search that video

### ISSUE THREAD

**Issue by ankit-sinha-18** [Achrou/goindex-theme-acrou#171]
whenever i open any video, it works smooth,, but upon searching the video by its name and tried to open, or copy link or download
it didn't work...
please fix this issue, so that file can be opened after searching also,,,,, otherwise search function is not useful without these functions....

**Comment by Achrou** [comment]
updated version

**Comment by alophim** [comment]
> phiên bản cập nhật


Play movies on iOS doesn't run well or have errors

**Comment by ankit-sinha-18** [comment]
I am not using iOS.

> updated  

> updated version

 I have made index two days ago... I have no problem in opening the video directly
But ,after searching the video and then playing
Then it doesn't respond

**Comment by ankit-sinha-18** [comment]
> > phiên bản cập nhật
> 
> Play movies on iOS doesn't run well or have errors

I am not using ios.
I am unable to open video after search of video .

**Comment by alophim** [comment]
You can watch this video when watching movies with such error and often
lose the sound I try a lot of devices in ios that error thank you for
taking care of me


Vào Th 4, 4 thg 11, 2020 lúc 16:33 ankit-sinha-18 <notifications@github.com>
đã viết:

**Comment by alophim** [comment]
https://youtu.be/0_2AkZ3KYQ8


Vào Th 4, 4 thg 11, 2020 lúc 16:40 tiến nguyễn <alophim.org@gmail.com> đã
viết:
