### ISSUE TITLE
You can watch this video when watching movies with such error and often lose the sound I try a lot of devices in ios that error thank you for taking care of me

### ISSUE THREAD

**Issue by alophim** [Achrou/goindex-theme-acrou#173]
You can watch this video when watching movies with such error and often lose the sound I try a lot of devices in ios that error thank you for taking care of me
![unnamed](https://user-images.githubusercontent.com/72789098/98095478-3b735b00-1ebd-11eb-99bd-8ba9ab4c181d.jpg)

[video  error ios.zip](https://github.com/Achrou/goindex-theme-acrou/files/5486933/ios.zip)

**Comment by Achrou** [comment]
#56

**Comment by alophim** [comment]
> [# 56](https://github.com/Achrou/goindex-theme-acrou/issues/56)


I cannot access that link

**Comment by alophim** [comment]
Hope to have another latest update to fix that

**Comment by Achrou** [comment]
Problems with video encoding

**Comment by alophim** [comment]
> Sự cố với mã hóa video

What are you trying to do to avoid this problem so let me know
