### ISSUE TITLE
Please add for Subtitles

### ISSUE THREAD

**Issue by DKB0512** [Achrou/goindex-theme-acrou#174]
If I have a video with srt or ass subtitles in it, it's not showing while playing the video. Please add the support so it can directly detect like other players for srt or ass subtitles.

**Comment by ankit-sinha-18** [comment]
> If I have a video with srt or ass subtitles in it, it's not showing while playing the video. Please add the support so it can directly detect like other players for srt or ass subtitles.

Watch in vlc or mx player , and add subtitles
