### ISSUE TITLE
nplayer调用问题

### ISSUE THREAD

**Issue by ugokin** [Achrou/goindex-theme-acrou#181]
问下直接调用nplayer播放，API是什么，找了很多没有相关资料

**Comment by ugokin** [comment]
作者看到麻烦回下，vlc的api也行，万分感谢！！！！！！

**Comment by Achrou** [comment]
https://github.com/Achrou/goindex-theme-acrou/blob/facd77d7f9bc2858d2f50636b0b7ac4311fe402e/src/views/page/GoVideo.vue#L215
