### ISSUE TITLE
团队盘'.*'命名文件出问题

### ISSUE THREAD

**Issue by ntgeralt** [Achrou/goindex-theme-acrou#19]
反馈个问题：团队盘这种格式文件会导致出错（一直弹密码）
![image](https://user-images.githubusercontent.com/8230651/81286499-be913100-9093-11ea-954f-aee77064a969.png)

**Comment by ntgeralt** [comment]
再反馈个小小问题：
ios safari 支持度不佳（在线播放、切换盘）
瑕不掩瑜，你这个魔改是我接触过做得最好的。

**Comment by Achrou** [comment]
`.password`是设置文件夹密码的文件，如果是设置在根目录在切换到该盘时会要求输入密码进行验证，验证不通过则一直弹出。关于 `ios safari 支持度不佳（在线播放、切换盘）`不知道具体是哪方面？最后感谢你给与的肯定🤞

**Comment by ntgeralt** [comment]
@Aicirou 谢谢回复。
在ios 12.1 safari打开一个视频，‘等待视频连接中’一直没画面..点右上角三条杠没有换盘按钮。
（ios uc浏览器显示正常，三条杠能换盘，但'等待视频连接中'也一直没画面）
同样wifi科学环境，PC win正常 很快出影片画面；

pass留空，似乎还是读取.password文件。我填.password里面密码也不正确，一直弹窗；
请教改哪里可以不去读.password

**Comment by Achrou** [comment]
我试下来（mkv,webm）最新版本的macos safari情况稍微好些多刷几次可以出来，而ios不管什么版本这两种格式都出不来了。至于mp4，macos和ios不管哪个版本肯定可以打开。

**Comment by Achrou** [comment]
去除密码校验：`index.js`中搜索`check password`注释掉266-273行代码即可

**Comment by Achrou** [comment]
ios safari 右侧导航菜单点击没反应还是只是没有多盘的切换

**Comment by ntgeralt** [comment]
ios safari能点开搜索，没多盘切换；您有空的时候再看看啦

check password下面7行注释掉果然可以

**Comment by Achrou** [comment]
右侧导航菜单的问题尝试清理下缓存试试吧，右侧导航菜单受样式所控，一般不会出现兼容问题
