### ISSUE TITLE
Subtitles

### ISSUE THREAD

**Issue by ghost** [Achrou/goindex-theme-acrou#190]
Any way to get .srt and .sub subtitles to work?

**Comment by Fiyaas** [comment]
> Criminal Justice(2019) S01 E01 WebRip z -  mkvCinemas.mkv

**Comment by ghost** [comment]
> > Criminal Justice(2019) S01 E01 WebRip z -  mkvCinemas.mkv

Sorry?

**Comment by Achrou** [comment]
Only support vtt

**Comment by ghost** [comment]
Yes ended up converting the srt files to vtt :)
Usimg this
https://github.com/nwoltman/srt-to-vtt-cl
U should mention this so that same question isn't raised again 😅 
Also 10bit video is black in the browser
Most probably because browsers don't support it right?

**Comment by Achrou** [comment]
![image](https://user-images.githubusercontent.com/32474991/103125925-b1c75900-46c7-11eb-8f44-3ca65b66cb08.png)
x265 encoded video requires browser support
