### ISSUE TITLE
Help 

### ISSUE THREAD

**Issue by ghost** [Achrou/goindex-theme-acrou#193]
I am trying to use exo player instead of the one u gave
https://github.com/google/ExoPlayer
How do i use this
Since in the wiki u said support for custom player (api)
:( 
The default one is very good but sometimes subtitles with the video doesn't play :3 vtt ones work though but i have some videos where subtitles are with video and can be turned on and off

**Comment by Achrou** [comment]
1. the player needs to be a web project
2. provide an api to receive video addresses, similar to https://xx.xx/?url=

**Comment by ghost** [comment]
> 1. the player needs to be a web project
> 2. provide an api to receive video addresses, similar to https://xx.xx/?url=

Do u know why the subtitles are not playing?
It softcoded and muxed
Does the player only use vtt subtiles and not those?

**Comment by Achrou** [comment]
If you just want to play video files with embedded subtitles you can try the following ways to play them (requires the corresponding software installed on the device)
![image](https://user-images.githubusercontent.com/32474991/103133346-ebf32380-46e4-11eb-9904-c04e5d768d10.png)

**Comment by ghost** [comment]
So player can't use embedded right? Ok
I will try to extract subtitles then

**Comment by ghost** [comment]
in movies the vtt subtitles are not loading 
but in series episodes they work :(
strange only happening with movies that subtitles not working
![image](https://user-images.githubusercontent.com/46019727/103134970-f1e60600-46de-11eb-9764-8a284c6656ed.png)
