### ISSUE TITLE
如何设置GoIndex能用的自己的Google Client ID？

### ISSUE THREAD

**Issue by MFYDev** [Achrou/goindex-theme-acrou#199]
感谢Achrou开源此程序！

我在切换到自己的Google Client ID时遇到了问题，目前Google Client ID适用范围没有`其他选项`，推测可用的是`Web应用`和`桌面应用`，所以我的设置步骤如下：

1. 选择桌面应用，获取client id 和 secret
2. 开启Google Drive API
3. OAUTH同意屏幕里面允许所有Google Drive权限，域名设置为我自己的goindex域名
4. refresh_token使用我自己的token，这个确定无误

但是此方法导致的直接结果就是所有文件无显示，将client id和secret切换回您的之后一切又正常。

请问哪里做错了呢？或者有任何教程吗？

**Comment by MFYDev** [comment]
已解决

**Comment by Dragon-son** [comment]
> 已解决

请问怎么解决的

**Comment by ckx000** [comment]
> > 已解决
> 
> 请问怎么解决的

生成Authorization Code的时候就必须要用自己的client id 和 secret，然后再用它们生成refresh_token
