### ISSUE TITLE
【求助】使用app.js却无法搜索

### ISSUE THREAD

**Issue by baby1128** [Achrou/goindex-theme-acrou#2]
按照使用说法，直接修改了app,js的内容，模板是改成功了，但是却无法搜索，不知道是哪里有问题。
尝试用大佬自己的页面却是却可以搜索，是不是需要自己下载文件上传之后才能使用？（小白不懂怎么操作这一步）
麻烦大佬指导，谢谢~

**Comment by Achrou** [comment]
> 按照使用方式，直接修改了app，js的内容，模板是改成功了，但是却无法搜索，不知道是哪里有问题。
> 尝试用大佬自己的页面却是却可以搜索，是不是需要自己下载文件解决之后才能使用？（小白不懂怎么操作这一步）麻烦
> 大佬指导，谢谢〜

搜索需要在index文件添加方法，这个是添加了搜索方法的[index.js](https://oss.achirou.workers.dev/go2index/index.js)

**Comment by baby1128** [comment]
成功了，谢谢@Aicirou
