### ISSUE TITLE
用外部播放器播放时，能同时关联当前文件夹的同名字幕吗

### ISSUE THREAD

**Issue by ssyangchn** [Achrou/goindex-theme-acrou#202]

**Comment by Achrou** [comment]
需要外部播放器自行去加载同名字幕文件

**Comment by ssyangchn** [comment]
> 需要外部播放器自行去加载同名字幕文件

直接在网页上看，也没有加载同名字幕

**Comment by Achrou** [comment]
首先视频所在目录下你得有字幕文件，然后播放器要打开字幕开关，再然后字幕文件只支持vtt格式

**Comment by ssyangchn** [comment]
> 首先视频所在目录下你得有字幕文件，然后播放器要打开字幕开关，再然后字幕文件只支持vtt格式

难怪，我是ass的字幕
