### ISSUE TITLE
Filename on the video player page - GoVideo.vue

### ISSUE THREAD

**Issue by viper-adnan** [Achrou/goindex-theme-acrou#205]
Filename should be shown on the video player page. If you are not working on this project currently, please tell me how to get the filename in the `GoVideo.vue` file. I need a example.
Thanks —

**Comment by Achrou** [comment]
https://github.com/Achrou/goindex-theme-acrou/blob/facd77d7f9bc2858d2f50636b0b7ac4311fe402e/src/views/page/GoVideo.vue#L94
`console.log(this.$router)` the relevant parameters are found here
