### ISSUE TITLE
Video player fail when load

### ISSUE THREAD

**Issue by vanlongme** [Achrou/goindex-theme-acrou#22]
![image](https://user-images.githubusercontent.com/30171328/81481444-7c661c00-925a-11ea-86f4-2ad54eaa5222.png)
It seem like your cdn server had down and video player couldn't start, please check !

**Comment by Achrou** [comment]
The latest version already supports custom video player, you can upgrade to the latest version

**Comment by vanlongme** [comment]
Well, but i want to using this player to embed on my website, may you fix it ? Is it possible on future ?

**Comment by Achrou** [comment]
I'll optimize it if I have time

**Comment by vanlongme** [comment]
Many thanks, hope see you soon !!!
