### ISSUE TITLE
时不时网页无响应

### ISSUE THREAD

**Issue by Tony-Yes** [Achrou/goindex-theme-acrou#232]
加载出来空白，没有文件和 文件夹，这是什么问题？

**Comment by Achrou** [comment]
换成自己的client_id、client_secret、refresh_token

**Comment by Tony-Yes** [comment]
改了之后直接加载不出来，空白文件夹😅

**Comment by gerryfu** [comment]
我也是，改了自己的client_id、client_secret、refresh_token。依然都是一片空白。

相对用另外一个goindex的脚本，就可以。
