### ISSUE TITLE
VLC url issue

### ISSUE THREAD

**Issue by pctechkid** [Achrou/goindex-theme-acrou#25]
Found a bug in which if the url of the video played with vlc contains characters like '[' and ']' example:
```js
vlc://https://example.yoursitehere.workers.dev/The%20Platform%20[2020].mkv
```

The vlc can't play the link, but if the '[' character is changed to %5B and the ']' into %5D , the vlc plays the url and works perfectly as it should. The final url should be:
```js
vlc://https://example.yoursitehere.workers.dev/The%20Platform%20%5B2020%5D.mkv
```
Please try to fix it. Thank you.

**Comment by Achrou** [comment]
resolved
