### ISSUE TITLE
Pdf Viewer Issue

### ISSUE THREAD

**Issue by bluearash** [Achrou/goindex-theme-acrou#256]
Hello and thank you for the opportunity.
I had a problem with PDF files. On the WordPress site, with the HappyAddons-PDF Viewer plugin, instead of displaying the file, it starts downloading the file.
Do you think there is a solution to this problem?
Thanks

**Comment by Achrou** [comment]
The link to the preview should be used instead of the download link

**Comment by bluearash** [comment]
Thanks for the reply
How do I create a preview link?

**Comment by Achrou** [comment]
/0:down/..... Use links without "down"

**Comment by bluearash** [comment]
For example, I use the following link. But the problem remains:
**https://dl16.acedco.com/0:/BiuldingRules/Mabhas-01-1392-V1.pdf**

Do I have to change this link?

**Comment by Achrou** [comment]
I found this to be a bug in the judgment logic that can be removed `!` Solve this problem
https://github.com/Achrou/goindex-theme-acrou/blob/facd77d7f9bc2858d2f50636b0b7ac4311fe402e/go2index/index.js#L327

**Comment by Achrou** [comment]
> For example, I use the following link. But the problem remains: **https://dl16.acedco.com/0:/BiuldingRules/Mabhas-01-1392-V1.pdf**
> 
> Do I have to change this link?

Hi, please confirm if you have changed the program; the standard program can be previewed normally https://ossdev.node6.workers.dev/0:/Issues%20test/Mabhas-01-1392-V1.pdf

**Comment by bluearash** [comment]
Excellent, Good job
Your link is working properly. While this is not the case with my link. But I do not understand the difference between these two links.

**Comment by bluearash** [comment]
I checked your page (https://ossdev.node6.workers.dev/) was different from my page (https://dl16.acedco.com). I will send the script text inside the Cloud Flare Worker in the attached file. 
Maybe the problem will be identified.

[Dl16-Worker.txt](https://github.com/Achrou/goindex-theme-acrou/files/8874538/Dl16-Worker.txt)

**Comment by bluearash** [comment]
Hello again
Do you have any idea about my problem?
