### ISSUE TITLE
wiki提供的index.js无法搜索

### ISSUE THREAD

**Issue by superxxl** [Achrou/goindex-theme-acrou#26]
```
Replace index.js with index.js
Modify the app.js used in index.js of goindex to https://cloud.jsonpop.cn/go2index/last/app.mini.js
```
1.修改认证信息后，将index.js填入cloudflare
2.试图搜索文件，无效
疑惑：wiki演示站又可以搜索，是否wiki的文件不一致，或是没有更新

**Comment by Achrou** [comment]
`index.js`使用的是README里说的吗

**Comment by superxxl** [comment]
是的，可以访问

**Comment by Achrou** [comment]
之前使用过这个cdn地址吗?如果使用过，应该是缓存问题，清下浏览器缓存就好了

**Comment by superxxl** [comment]
依旧不可以用，想必不是缓存的原因，换个浏览器，换个子域名，搜索都无效

**Comment by Achrou** [comment]
如果可以的话贴个地址出来 或者 #15 有交流群的二维码，你可以加一下

**Comment by superxxl** [comment]
https://dev.supervideo.workers.dev
用的文件中的index

**Comment by superxxl** [comment]
大佬看看有什么问题不

**Comment by Achrou** [comment]
主题版本是对的，问题出在index.js上，你应该修改过

**Comment by superxxl** [comment]
https://dev.supervideo.workers.dev/0:/index.js?a=view
只修改了token认证这些东西，我等会再重建api一遍，实在不行就算了，感谢大佬的回复

**Comment by Achrou** [comment]
你贴出来的这个index.js文件也没问题，你可以用cloudflare调试一下，看看是不是auth的问题

**Comment by superxxl** [comment]
已解决，谢谢大佬
