### ISSUE TITLE
关于favicon和加载背景图

### ISSUE THREAD

**Issue by sunpma** [Achrou/goindex-theme-acrou#28]
看见大佬在弄2.0版本的，不知能否加上一个自定义favicon.ico的功能呢？
以前本来有一个默认的favicon.ico，现在也没有了
还有加载时的背景图能否提供一张非二次元图片的选择呢？
如果都能自定义那就完美了，大佬满足下吧，十分感谢

最后一个问题：地址栏都有一个`/0:/`是怎么回事呢？

**Comment by Achrou** [comment]
1. 为了扩展性去掉了默认favicon.ico,自定义favicon.ico在head里加上就行了
2. 至于背景图之前随手加了一张，我也一直好奇为什么没人说，还以为都喜欢
3. /0:/相当于盘符吧，多个盘依次就是 0,1,2,3....

**Comment by sunpma** [comment]
好的，明白了，不过这地址栏显示盘符确实有点丑，哈哈
希望有可以替换的背景图，感谢大佬，辛苦了~
