### ISSUE TITLE
移动端搜索框

### ISSUE THREAD

**Issue by sorrymyself** [Achrou/goindex-theme-acrou#3]
大佬，能适配下移动端的搜索框吗，手机打开找不到搜索框

**Comment by Achrou** [comment]
> 大佬，能适配下移动端的搜索框吗，手机打开找不到搜索框

已经适配了，清下缓存就能看到效果了

**Comment by sorrymyself** [comment]
还有一个问题，搜索功能，有点不好使。二级目录基本搜不到
2020年4月22日 +0800 16:05 Aicirou <notifications@github.com>，写道：

**Comment by Achrou** [comment]
> 还有一个问题，搜索功能，有点不好使。二级目录基本搜不到 2020年4月22日 +0800 16:05 Aicirou <notifications@github.com>，写道：
> […](#)
> > 大佬，能适配下移动端的搜索框吗，手机打开找不到搜索框 已经适配了，清下缓存就能看到效果了 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

现在搜索只能进行简单的搜索，后面会支持表达式实现更高级的搜索

**Comment by sorrymyself** [comment]
good
2020年4月22日 +0800 16:10 Aicirou <notifications@github.com>，写道：

**Comment by AnshumanFauzdar** [comment]
Search for team drive is also not working!

**Comment by Achrou** [comment]
> Search for team drive is also not working!

Now it supports simple search. How do you operate it?

**Comment by AnshumanFauzdar** [comment]
It is not searching at all, Page gets refreshed
I followed all the steps

**Comment by Achrou** [comment]
The goindex author's index.js does not support search. Use this [index.js](https://oss.achirou.workers.dev/go2index/index.js?a=view) if you need a search function.

**Comment by AnshumanFauzdar** [comment]
Hey, Now its working but by applying password nothing opens
Without password working fine!
Search is only working for files, not for directories - link gets generated in same root folder so doesnot opens up!

**Comment by Achrou** [comment]
Yes, password support is still a problem. The next version will solve this problem.

**Comment by AnshumanFauzdar** [comment]
Thank you @Aicirou

**Comment by Achrou** [comment]
HTTP basic auth was added to solve the problem of bypassing the password through search
