### ISSUE TITLE
无法显示出搜索框

### ISSUE THREAD

**Issue by Yxue-1906** [Achrou/goindex-theme-acrou#36]
如题，虽然在注释中看到了“设置为子目录id的盘不支持搜索”，能具体一点吗？
另外，我使用原版（指yanzai/goindex）时是可以有搜索框的

**Comment by Achrou** [comment]
因为子目录id不支持搜索，所以搜索框会隐藏掉。yanzai/goindex也一样

**Comment by Yxue-1906** [comment]
emm，意思是只有root和团队盘的根目录可以有搜索框是吗？
我换回去试试，我印象中是有搜索框的。。也许记错了
