### ISSUE TITLE
问题反馈

### ISSUE THREAD

**Issue by Yxue-1906** [Achrou/goindex-theme-acrou#37]
有时候会出现进入播放页之后闪回到上一页甚至上上一页
开启全局密码验证后有时会出现进入时已经验证过，但是播放时又弹出验证窗口
另外，页面上的排序方式无法更改

另外请求添加一个下载按钮

**Comment by Achrou** [comment]
先暂时避免分页加载的时候跳转新的页面吧，下个版本修复这个bug。哪个页面要加下载按钮？列表页面是有下载按钮的

**Comment by Yxue-1906** [comment]
> 先暂时避免分页加载的时候跳转新的页面吧，下个版本修复这个bug。哪个页面要加下载按钮？列表页面是有下载按钮的

希望在视频播放页也添加下载按钮，主要是以前的用习惯了（既然列表有的话也可以不用管了吧

**Comment by Achrou** [comment]
排序是留给以后的版本的,现版本仅展示。便于操作的建议会考虑添加的
