### ISSUE TITLE
flv 无法在线播放

### ISSUE THREAD

**Issue by fzfile** [Achrou/goindex-theme-acrou#38]
如题，传了几个flv，发现点击文件只能下载，不能在线观看。

**Comment by Achrou** [comment]
最好贴个地址

**Comment by fzfile** [comment]
https://jav.fzserver.workers.dev/1:/%E5%8A%A8%E7%94%BB/

**Comment by MCSeekeri** [comment]
令人悲伤的是.......我也出现了....
链接[在此](https://sgalpha.mcseekeri.workers.dev/0:/%E5%91%BD%E8%BF%90%E7%9F%B3%E4%B9%8B%E9%97%A8%20%E5%8A%A8%E7%94%BB/%E6%AF%94%E5%88%A9%E6%AF%94%E5%88%A9%E7%89%88/)
我真心是很需要这个功能的......

**Comment by fzfile** [comment]
> 令人悲伤的是.......我也出现了....
> 链接[在此](https://sgalpha.mcseekeri.workers.dev/0:/%E5%91%BD%E8%BF%90%E7%9F%B3%E4%B9%8B%E9%97%A8%20%E5%8A%A8%E7%94%BB/%E6%AF%94%E5%88%A9%E6%AF%94%E5%88%A9%E7%89%88/)
> 我真心是很需要这个功能的......

我直接把flv添加到支持的格式里，页面倒是能开，不过前端播放器貌似不支持，倒是意外发现mov可以。。。。

**Comment by alimalls** [comment]
https://gd.360safe.cloud/0:/%E7%A6%81%E5%8C%BA/%E6%96%B0%E7%95%AA2020/%E9%9F%A9%E5%9B%BD%E5%A5%B3%E4%B8%BB%E6%92%AD/%E5%B0%8F%E9%92%9F%E6%B7%91/014.flv  我也是遇到FLV无法播放，作者有空看看是什么原因引起的。感谢开发这么好的程序
