### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by mlwbd** [Achrou/goindex-theme-acrou#47]
It failed to play videos which are ×265 hevc encoded.
Also it is great if it support for choosing resolution

**Comment by mlwbd** [comment]
See the difference
![68747470733a2f2f692e696d6775722e636f6d2f5939704a6f31562e706e67](https://user-images.githubusercontent.com/48172226/83321713-1542f280-a26f-11ea-9494-9fd808f68edd.png)
![Screenshot_2020-05-30-12-13-36-358_com android chrome](https://user-images.githubusercontent.com/48172226/83321717-1ecc5a80-a26f-11ea-8f54-8ecaa1e75f72.jpg)

**Comment by Achrou** [comment]
×265  hevc encoded requires browser support
