### ISSUE TITLE
【BUG】最新版本，播放视频刚打开就闪退，之后连文件夹都进不去

### ISSUE THREAD

**Issue by gimgoo** [Achrou/goindex-theme-acrou#51]
如题，最新版本，播放视频刚打开没几秒就闪退回主目录，之后连存放该视频的文件夹都进不去。

**Comment by Achrou** [comment]
原因看这个[#37](https://github.com/Aicirou/goindex-theme-acrou/issues/37#issuecomment-634087298)，此问题已修复，但目前快速部署程序还没发布最新版本，你可以手动切到2.0.5分支获取最新版本，或者等我明天发最新版本

**Comment by Achrou** [comment]
快速部署程序已支持最新版本
