### ISSUE TITLE
关于文件夹描述

### ISSUE THREAD

**Issue by 1035833776** [Achrou/goindex-theme-acrou#53]
请问下文件夹描述该怎么弄，我看到js注释里有这个开关，但不知道该怎么添加？可以告知下吗？感谢了！

**Comment by jzysl123** [comment]
打开https://drive.google.com/
选中一个文件 点开右上角查看详细信息 添加说明里面就是文件夹描述

**Comment by 1035833776** [comment]
感谢告知！

**Comment by 1035833776** [comment]
> 打开https://drive.google.com/
> 选中一个文件 点开右上角查看详细信息 添加说明里面就是文件夹描述

感谢告知！
