### ISSUE TITLE
i18n question

### ISSUE THREAD

**Issue by orezraey** [Achrou/goindex-theme-acrou#55]
How Can I set up another language to index? I would like to switch from English to Portuguese. Can I change that in cloudflare script or I need to deploy with Rclone to do?

**Comment by Achrou** [comment]
Sorry, Spanish is not supported now. If possible, could you please help to translate a document in Spanish. [en.json](https://github.com/Aicirou/goindex-theme-acrou/blob/master/src/locales/en.json)

**Comment by orezraey** [comment]
Not Spanish. I said Portuguese. Portuguese isn't supported also?

**Comment by orezraey** [comment]
> 
> 
> Sorry, Spanish is not supported now. If possible, could you please help to translate a document in Spanish. [en.json](https://github.com/Aicirou/goindex-theme-acrou/blob/master/src/locales/en.json)

I do it. Hope that you add portuguese lang when possible :))
