### ISSUE TITLE
第十个团队盘开始无法打开。

### ISSUE THREAD

**Issue by Cosmos-Break** [Achrou/goindex-theme-acrou#59]
http://gd.aria2c.fun/10:/

**Comment by Cosmos-Break** [comment]
test

**Comment by IDforHYIT** [comment]
同遇到，盘符10包括及之后的盘数据页面貌似数据都加载不进来，页面显示高度貌似也有问题😂
![image](https://user-images.githubusercontent.com/41300598/84776933-862a2e80-b013-11ea-8ab3-2fe7d4bb442c.png)
