### ISSUE TITLE
在线播放视频只有声音没有画面（黑屏）

### ISSUE THREAD

**Issue by bearngrin** [Achrou/goindex-theme-acrou#62]
例如：mp4文件：https://nv.nltrans.workers.dev/1:/Learning/Stanford-Intro%20to%20CS/CS106A/Copy%20of%20cs106a-lecture01.mp4
mkv文件：https://nv.nltrans.workers.dev/0:/%5BUXN%5D%20%E4%BF%A1%E5%8F%B7.%EC%8B%9C%EA%B7%B8%EB%84%90.COMPLETE.UHDTV.60fps.x265.AAC.2160p-Once/%5BUXN%5D%20%EC%8B%9C%EA%B7%B8%EB%84%90.E01.UHDTV.60fps.x265.AAC.2160p-Once.mkv

**Comment by Achrou** [comment]
#56

**Comment by bearngrin** [comment]
谢谢。用Edge试了一下，第二个x265编码的有画面了。但是第一个.mp4格式的还是没有画面（以前用另一个goindex脚本能正常播放），应该不是格式问题，能帮忙分析一下原因吗？
