### ISSUE TITLE
Edge浏览器播放mp4无画面

### ISSUE THREAD

**Issue by bearngrin** [Achrou/goindex-theme-acrou#63]
https://github.com/Aicirou/goindex-theme-acrou/issues/62#issue-632954382

不好意思，刚才那个问题只解决了一半。x265编码的文件换Edge浏览器播放正常了，但那个mp4格式的在Edge中播放还是只有声音没有画面（不是文件本身问题，Gdrive在线及其他goindex代码试过可以播放）。链接如下：
https://nv.nltrans.workers.dev/1:/Learning/Stanford-Intro%20to%20CS/CS106A/Copy%20of%20cs106a-lecture01.mp4

麻烦帮忙分析一下原因，谢谢！

**Comment by Achrou** [comment]
浏览器打开视频地址，如果浏览器自带的都不行，那网页播放器也无能为力
