### ISSUE TITLE
为什么不在这个项目加一个暗黑模式的分支呢

### ISSUE THREAD

**Issue by sorrymyself** [Achrou/goindex-theme-acrou#64]
反而换了个账号

**Comment by Achrou** [comment]
因为那是别人改的

**Comment by sorrymyself** [comment]
我不管，我就要改一个
2020年6月7日 +0800 20:27 Aicirou <notifications@github.com>，写道：

**Comment by Achrou** [comment]
喜欢dark，就先用着第三方的呗

**Comment by sorrymyself** [comment]
要你
2020年6月7日 +0800 20:27 Aicirou <notifications@github.com>，写道：

**Comment by sorrymyself** [comment]
我不用，我就要等你
2020年6月7日 +0800 20:31 Aicirou <notifications@github.com>，写道：

**Comment by a532233648** [comment]
> 因为那是别人改的

大佬还是改个吧，那边没有及时更新，大佬后面这一版修改的bug（比如无法预览的点击无法下载）就没有跟上，希望大佬出一个

**Comment by Achrou** [comment]
该有的都会有

**Comment by sorrymyself** [comment]
就等你这句话了
2020年6月7日 +0800 22:07 Aicirou <notifications@github.com>，写道：
