### ISSUE TITLE
提取直连问题

### ISSUE THREAD

**Issue by zyk445971319** [Achrou/goindex-theme-acrou#7]
感谢大佬解决之前的中文搜索问题，想再请求大佬，能否加入一个提取直连的按钮 迅雷用的比较少 这样方便用idm等工具下载

**Comment by zyk445971319** [comment]
详细点是手机页面视频播放页面加一个直连按钮

**Comment by Achrou** [comment]
已经在视频页面将直连地址显示出来了，清缓存就能看到效果
