### ISSUE TITLE
Subtitle (closed caption) support

### ISSUE THREAD

**Issue by louanfontenele** [Achrou/goindex-theme-acrou#75]
Please, if possible, add Closed Caption (Subtitle) support. Example: A video called example.mp4 and have a file called example.vtt - the player can recognize the subtitle name as the same of the video, so, always when a file directory has a video and a .vtt file, will show the subtitle, if don't have it, won't show nothing.

**Comment by Achrou** [comment]
Aicirou/goindex-theme-acrou@4a098d3

**Comment by louanfontenele** [comment]
> [4a098d3](https://github.com/Aicirou/goindex-theme-acrou/commit/4a098d3)

Thanks, works now <3
