### ISSUE TITLE
添加flac、wav、mp3、m4a、wma、ogg等音频文件在线播放

### ISSUE THREAD

**Issue by reddloob** [Achrou/goindex-theme-acrou#77]
![QQ拼音截图20200615183314](https://user-images.githubusercontent.com/46004053/84647961-cb2c6300-af36-11ea-8458-8c1da8f4c5af.png)
![QQ拼音截图20200615183643](https://user-images.githubusercontent.com/46004053/84648162-30805400-af37-11ea-9e16-1d0c352faeef.png)

goindex/themes/material/app.js /，原修改版支持音频文件在线播放，希望能够尽快增改该功能

**Comment by reddloob** [comment]
自己改了一下，在默认播放器里加了几个音频格式，竟然能用~
goindex-theme-acrou/dist/js/app.e49c59b7.js文件里改这个
 i = ["mp4", "webm", "mkv", "m3u8", "flac", "wav", "mp3", "m4a", "wma", "ogg"],

还是希望作者能设计一个专门的音乐播放，用h5播放器没法显示专辑封面、没法加载lrc歌词，还是差点意思~

**Comment by realnli** [comment]
> 自己改了一下，在默认播放器里加了几个音频格式，竟然能用~
> goindex-theme-acrou/dist/js/app.e49c59b7.js文件里改这个
> i = ["mp4", "webm", "mkv", "m3u8", "flac", "wav", "mp3", "m4a", "wma", "ogg"],
> 
> 还是希望作者能设计一个专门的音乐播放，用h5播放器没法显示专辑封面、没法加载lrc歌词，还是差点意思~

请问这个怎么部署啊，是在worker的代码里吗？

**Comment by gohhh1234** [comment]
请问这个怎么部署啊，是在worker的代码里吗？
