### ISSUE TITLE
ipad端打开网页直接是空白显示 不知道哪里的问题

### ISSUE THREAD

**Issue by Achrou** [Achrou/goindex-theme-acrou#8]
@Aicirou ipad端打开网页直接是空白显示 不知道哪里的问题

_Originally posted by @jzysl123 in https://github.com/Aicirou/goindex-theme-acrou/issues/4#issuecomment-621575708_

**Comment by jzysl123** [comment]
清理过缓存了  pc端只有谷歌内核浏览器才能打开  ie11打开也是空白  ios10可能浏览器不支持

**Comment by jzysl123** [comment]
应该是不兼容低版本的系统和浏览器  刚刚在安卓雷电模拟器小米版3.65中也是空白

**Comment by Achrou** [comment]
是版本问题，一开始的时候就打算不考虑低版本兼容的问题，现在看来还是要适当兼容一些不算太老的版本或者给个提示
