### ISSUE TITLE
小小建議

### ISSUE THREAD

**Issue by aaronlin0122** [Achrou/goindex-theme-acrou#80]
Grid View:
若資料夾裡有圖片，可以使用圖片當作資料夾的預覽圖。(可從設定中開關）

**Comment by Achrou** [comment]
這麼做會增加渲染成本（如果是文件夾然後去查詢該文件夾下的文件並且判斷是否是圖片），會導致速度非常慢，弊大於利

**Comment by NekoChan-2851** [comment]
如果是自訂的檔名當預覽圖有可能嗎

**Comment by Achrou** [comment]
需求非大眾化，你可以按照自身需求調整代碼構建自己的程序

**Comment by aaronlin0122** [comment]
好的
