### ISSUE TITLE
Download

### ISSUE THREAD

**Issue by darkparky** [Achrou/goindex-theme-acrou#83]
Download button not working

**Comment by Achrou** [comment]
Please be more specific.

**Comment by SageOfD6Path** [comment]
The download button below the streaming tab doesn't work. In case of accessing it from pc we don't have a problem, there is a separate download, copy and open in new tab button. However the index isn't well optimised for mobile and so users have to open the file and hence there the download button doesn't work, users have to copy download link manually and then download.
![Screenshot_20200625-203907836](https://user-images.githubusercontent.com/62869599/85746259-dbda9700-b6f5-11ea-96b0-b5e2b1e4a52c.jpg)

**Comment by DKB0512** [comment]
Yes I have the same issue. Please fix that download button so that users can easily download the file instead of copy pasting the download link :)

**Comment by Achrou** [comment]
Aicirou/goindex-theme-acrou@a75e1d4c0e5e051250225671ef24ada5b2f7f4b1
