### ISSUE TITLE
希望添加字幕功能

### ISSUE THREAD

**Issue by Yxue-1906** [Achrou/goindex-theme-acrou#84]
如题,在阅读dplayer的文档时提到可以添加字幕,希望能自动匹配当前目录下的外挂字幕

如果能加载mkv的内部外挂字幕就更好了

感谢大佬付出

**Comment by ssyangchn** [comment]
复议

**Comment by Aicirou** [comment]
#4a098d3

**Comment by Achrou** [comment]
Aicirou/goindex-theme-acrou@4a098d3
