### ISSUE TITLE
More than 10 drive not working.. please fix it

### ISSUE THREAD

**Issue by prabha-coder** [Achrou/goindex-theme-acrou#85]
I have added 25 drive and its showing on dropdown. when i select the drive after 10th drive, it's not working.. please someone help to fix it..

**Comment by Achrou** [comment]
Fix it in the next version

**Comment by temporhodes** [comment]
> I have added 25 drive and its showing on dropdown. when i select the drive after 10th drive, it's not working.. please someone help to fix it..

How did you add multiple TDs ? there is only 1 spot for refresh token.but each TD has is own token.
how to edit index.js for this ?

tnx.

**Comment by panchalrajan** [comment]
> > I have added 25 drive and its showing on dropdown. when i select the drive after 10th drive, it's not working.. please someone help to fix it..
> 
> How did you add multiple TDs ? there is only 1 spot for refresh token.but each TD has is own token.
> how to edit index.js for this ?
> 
> tnx.

All TD should be in same account

**Comment by prabha-coder** [comment]
> 
> 
> > I have added 25 drive and its showing on dropdown. when i select the drive after 10th drive, it's not working.. please someone help to fix it..
> 
> How did you add multiple TDs ? there is only 1 spot for refresh token.but each TD has is own token.
> how to edit index.js for this ?
> 
> tnx.

**Comment by prabha-coder** [comment]
> 
> 
> Fix it in the next version
Dear @Aicirou 

when will you release the next version ? I'm using Dark Mode of Your Theme.. It looks great but not fully satisfied with mobile version. Please make it more response in mobile and make  size option in mobile would be great !

Appreciated for Your Work !!
