### ISSUE TITLE
Cannot find search box as in Demo site

### ISSUE THREAD

**Issue by NSKSW** [Achrou/goindex-theme-acrou#87]
Not able to find the search box as in demo site.

**Comment by Achrou** [comment]
Are you sure?

**Comment by NSKSW** [comment]
Yes, initially I put the sub-folder ID and no search box appears. I just tested with root folder ID now and can see search box. Seem like search box does not work with sub folder.

**Comment by Achrou** [comment]
You just said that the demo site doesn't have a search box. Subdirectories don't support search

**Comment by NSKSW** [comment]
What I meant was not able to see search box. Anyway, I got it now thanks.

**Comment by Achrou** [comment]
ok
