### ISSUE TITLE
.iso file issue

### ISSUE THREAD

**Issue by pctechkid** [Achrou/goindex-theme-acrou#88]
.iso files wont be downloaded in mobile browsers when clicked, instead it opens the image file preview with infinite loading.

**Comment by Achrou** [comment]
Can I have a link?

**Comment by pctechkid** [comment]
> Can I have a link?

```js
https://sample.nnel.workers.dev/0:/Windows%2010%20Pro%20version%2020H2%20(19042.330)%20amd64/
```

**Comment by Achrou** [comment]
The mimeType of this file is "application/x-iso9660-image" and it is treated as an image. Fix it in the next release
