### ISSUE TITLE
External player support

### ISSUE THREAD

**Issue by Achrou** [Achrou/goindex-theme-acrou#9]
请在这里提出你想要支持的播放器。
Please put forward the player you want to support here.

**Comment by zyk445971319** [comment]
手机播放视频页面请求支持IDM直链下载

**Comment by Achrou** [comment]
@zyk445971319 没有找到IDM的URL Scheme，可能是不支持吧，所以网页端没办法唤醒应用，不过我把直连地址显示出来了，你可以手动复制打开应用。清缓存就能看到了
