### ISSUE TITLE
播放问题

### ISSUE THREAD

**Issue by SHILEI-SPACE** [Achrou/goindex-theme-acrou#98]
为啥我的播放视频只有声，黑屏，没有画面，是我哪设置错了吗

**Comment by Achrou** [comment]
提问题之前为什么不先看看有没有相同的问题，这个问题已经pin在头顶很久了😓
![image](https://user-images.githubusercontent.com/32474991/86532602-ff73bd80-befd-11ea-934e-fc8a2567ca4c.png)
